### PR TITLE
New languages support

### PR DESCRIPTION
**Pull request by m0canu1**
Italian, French and German

### CODE REVIEW

**Comment by dvsrepo** [comment]
Hi @asterbini, this is great! Do you need any support testing this before merging?

**Comment by asterbini** [comment]
I'm just updating spacy-wordnet to spacy 3... Wait

**Comment by asterbini** [comment]
Yes, please do some tests. I've tried Italian in spacy3 and English both on spacy3 and spacy2

**Comment by frascuchon** [comment]
Hi @asterbini Thanks for your work.

We've just merge another PR including  spaCy 3.x upgrade (with backward compatibility)

Could you please, resolve conflicts with your branch?

**Comment by merlinico** [comment]
Any news on the conflict resolution ?

**Comment by LeMoussel** [comment]
Do you know when this PR will be merged? 
(I'd like to test for French)

**Comment by frascuchon** [comment]
Thanks @m0canu1 for your work

I will stabilize the branch in PR #16

**Pull request closed without merging**
